### ISSUE TITLE
Why two separate tf.matmul operations in BNLSTMCell.__call__?

### ISSUE THREAD

**Issue by carlthome** [OlavHN/bnlstm#5]
Is there a reason why [you're doing two separate tf.matmul](https://github.com/OlavHN/bnlstm/blob/master/lstm.py#L73-L74) instead of one large one (which would likely be faster)? E.g. `bn_lstm_identity_initializer` could initialize [2 * self.num_units, 4 * self.num_units] instead. I'm thinking it has something to do with wanting to keep the running means and variances separate for the input-to-hidden and hidden-to-hidden connections? Or is it just so that the input can be of a smaller size than the hidden state transitions?

**Comment by OlavHN** [comment]
The input and hidden states maybe different sizes, yes, but it would still be possible to have a single weight matrix of shape (x + h, 4h).

Note that the W_hh is initialized with the identity for a quarter of its weights. So that initializer would have to be a bit more complicated.

I remember them keeping the two batch norms separate in the paper, however by slicing the resulting matrix I think that would still be possible with your proposed optimization.

**Comment by OlavHN** [comment]
I see now that the pr by hardmaru actually concatenated the two weight matrices before the matmul for the vanilla lstm, thus keeping the initializers as they are. Same approach could work for the bnlstm.

**Comment by carlthome** [comment]
Concatenating would be neat for performance then. :+1: 

Yeah, I saw that you're using the identity for the input gate. I guess that's the fixed initialization proposed by Tim Cooijman?

**Comment by carlthome** [comment]
Thinking about this a little more. Actually, slicing would not work. There has to be two matrix multiplications if batch norm is supposed to be applied afterwards on both terms separately.

**Comment by carlthome** [comment]
Uh, which kinda answers my own question. Closing. :tada:
